CREATE TABLE api.bucket(
  id int PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  slug text NOT NULL UNIQUE,
  created_at timestamptz
);

INSERT INTO api.bucket(slug, created_at)
  VALUES ('bucket-1', now()),
('bucket-2', now());

