# docker-compose.yml

version: "3"
services:
  api:
    image: postgrest/postgrest
    ports:
      - "3000:3000"
    environment:
      PGRST_DB_ANON_ROLE: web_anon
      PGRST_DB_PRE_REQUEST: auth.check_token
      PGRST_DB_SCHEMAS: api
      PGRST_DB_URI: postgres://app_user:password@db:5432/app_db
      PGRST_JWT_SECRET: reallyreallyreallyreallyverysafe
      PGRST_OPENAPI_SERVER_PROXY_URI: http://127.0.0.1:3000
    depends_on:
      - db
  swagger:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      API_URL: http://localhost:3000
  db:
    image: postgres
    ports:
      - "5439:5432"
    environment:
      POSTGRES_DB: app_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: password
    volumes:
      - ./pgdata:/var/lib/postgresql/data
      - ./init-scripts:/docker-entrypoint-initdb.d
